[project]
name = "rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv",
    "langchain>=1.0.7",
    "pdfreader>=0.1.15",
    "python-dotenv>=1.2.1",
]
